apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mo58val33-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f7a8b5b1ff.pbwu.p3.openshiftapps.com/rhtap/rhtap-qe:d5593616ac070672b769bafc2c2c1f503c9bda33@sha256:212b747dd5a6d765049617e3a7297c4bf7b3b85c88b4b8e8a79d7200caa3368d
          name: container-image
